version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 99
  reviewers:
  - scherermichael
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  ignore:
  - dependency-name: "@sealsystems/eslint-config-es"
    versions:
    - ">= 0"
  - dependency-name: "@sealsystems/mocha"
    versions:
    - ">= 0"
  - dependency-name: "@sealsystems/semantic-release"
    versions:
    - ">= 0"
  - dependency-name: lodash
    versions:
    - 4.17.21
  - dependency-name: nodeenv
    versions:
    - 3.0.39
    - 3.0.40
    - 3.0.41
    - 3.0.42
    - 3.0.43
    - 3.0.44
    - 3.0.45
  commit-message:
    prefix: chore
    prefix-development: no-release
    include: scope
  registries:
  - npm-registry-npm-pkg-github-com
